version: '3.7'

services:
  keycloak-db:
      image: postgres:12
      volumes:
        - keycloak_postgres:/var/lib/postgresql/data
      env_file:
        - keycloak_db.env
      networks:
        - internal

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command:
        - start-dev
      env_file:
        - keycloak.env
      depends_on:
        - keycloak-db
      networks:
        - internal
        # - proxy-net
      ports:
        - 8443:8443
        - 8080:8080


volumes:
  keycloak_postgres:
      driver: local


networks:
  internal:
    driver: bridge
  # proxy-net:
    # name: pmd-reverse-proxy-net
    # external: true
