services:
  keycloak-db:
    image: postgres:12
    volumes:
      - keycloak_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - internal

  keycloak:
    build:
      dockerfile: Dockerfile
    command: ["start", "--optimized", "--http-enabled", "true"]
    # command: 
    #   - start-dev
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_SCHEMA=public
      - DB_DATABASE=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_CLIENT=admin-cli
      - KEYCLOAK_REALM=master
    depends_on:
      - keycloak-db
    networks:
      - internal
      - pmd-ds
    ports:
      - 8443:8443
      - 8080:8080

volumes:
  keycloak_postgres:
    driver: local

networks:
  pmd-ds:
    external: ${USE_EXTERNAL_PMD_DS_NETWORK}
  internal:
